export function prepareIllustrationSvg(raw: string): string {
  let out = raw
    .replace(/<!--[\s\S]*?-->\s*/g, "")
    .replace(/\r\n/g, "\n")
    .replace(/\sfill="none"\s/g, " ")
    .replace(/\bwidth="[^"]*"\s*height="[^"]*"\s*/g, "");

  // Keep the original strokes and fills, but ensure they are thick enough and use the ink color
  out = out.replace(/stroke-width="[^"]*"/g, 'stroke-width="3"');

  // Replace various dark brown/black colors generated by Quiver with our ink color
  out = out.replace(/#4a2c1f/gi, "var(--color-hs-ink)");
  out = out.replace(/#401a05/gi, "var(--color-hs-ink)");
  out = out.replace(/#33211a/gi, "var(--color-hs-ink)");
  out = out.replace(/#3f291e/gi, "var(--color-hs-ink)");
  out = out.replace(/#3b2719/gi, "var(--color-hs-ink)");
  out = out.replace(/#010b1b/gi, "var(--color-hs-ink)");
  out = out.replace(/#000000/gi, "var(--color-hs-ink)");
  out = out.replace(/#000\b/gi, "var(--color-hs-ink)");

  out = out.replace(
    /<svg\b/,
    '<svg focusable="false" aria-hidden="true" width="100%" height="100%" preserveAspectRatio="xMidYMid meet"'
  );

  return out;
}
